# Generated by Django 4.2.7 on 2023-11-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Finch',
        ),
    ]
